// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsPending() {
    return $Call.ByID(1814764663);
}

/**
 * @param {boolean} v
 * @returns {$CancellablePromise<void>}
 */
export function SetPending(v) {
    return $Call.ByID(1646223607, v);
}

/**
 * @param {$models.SessionAnswer} answer
 * @returns {$CancellablePromise<void>}
 */
export function SubmitAnswers(answer) {
    return $Call.ByID(2488090191, answer);
}
