// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class QuestionAnswer {
    /**
     * Creates a new QuestionAnswer instance.
     * @param {Partial<QuestionAnswer>} [$$source = {}] - The source object to create the QuestionAnswer.
     */
    constructor($$source = {}) {
        if (!("selectedIndexes" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["selectedIndexes"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["customText"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QuestionAnswer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QuestionAnswer}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("selectedIndexes" in $$parsedSource) {
            $$parsedSource["selectedIndexes"] = $$createField0_0($$parsedSource["selectedIndexes"]);
        }
        return new QuestionAnswer(/** @type {Partial<QuestionAnswer>} */($$parsedSource));
    }
}

export class SessionAnswer {
    /**
     * Creates a new SessionAnswer instance.
     * @param {Partial<SessionAnswer>} [$$source = {}] - The source object to create the SessionAnswer.
     */
    constructor($$source = {}) {
        if (!("answers" in $$source)) {
            /**
             * @member
             * @type {QuestionAnswer[]}
             */
            this["answers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionAnswer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionAnswer}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("answers" in $$parsedSource) {
            $$parsedSource["answers"] = $$createField0_0($$parsedSource["answers"]);
        }
        return new SessionAnswer(/** @type {Partial<SessionAnswer>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = QuestionAnswer.createFrom;
const $$createType2 = $Create.Array($$createType1);
